name: Build and Test

on: push

jobs:
  test-archive:
    runs-on: windows-latest
    steps:
      # Clone this repo
      - name: Checkout
        shell: bash
        run: |
          curl --location --user token:${{ github.token }} --output checkout.tar.gz https://api.github.com/repos/actions/checkout/tarball/${{ github.sha }}
          tar -xzf checkout.tar.gz
          mv */* ./

      # Basic checkout
      - name: Basic checkout
        uses: ./
        with:
          ref: test-data/v2/basic
          path: basic
      - name: Verify basic
        shell: bash
        run: __test__/verify-basic.sh container

